name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  test-endpoint:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package

      - name: Start Spring Boot application
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          nohup java -jar target/*.jar > app.log 2>&1 &
          echo "Waiting for app to start..."
          sleep 30
          curl --retry 5 --retry-delay 5 --retry-all-errors http://localhost:8080/ai/generate

      - name: Test /ai/generate endpoint
        run: |
          RESPONSE=$(curl -s -G --data-urlencode "message=Hello AI" http://localhost:8080/ai/generate)
          echo "Response: $RESPONSE"
          if [[ -z "$RESPONSE" ]]; then
            echo "Endpoint test failed!"
            exit 1
          fi
